apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cloudnotes-secrets-provider
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.global.projectId }}/secrets/{{ .Values.backend.secrets.dbPasswordSecret }}/versions/latest"
        fileName: "db-password"
      - resourceName: "projects/{{ .Values.global.projectId }}/secrets/{{ .Values.backend.secrets.mongodbUriSecret }}/versions/latest"
        fileName: "mongodb-uri"
      - resourceName: "projects/{{ .Values.global.projectId }}/secrets/{{ .Values.backend.secrets.jwtSecretSecret }}/versions/latest"
        fileName: "jwt-secret"
  secretObjects:
    - secretName: cloudnotes-backend-secret-sync
      type: Opaque
      data:
        - objectName: db-password
          key: DB_PASSWORD
        - objectName: mongodb-uri
          key: MONGODB_URI
        - objectName: jwt-secret
          key: JWT_SECRET
