apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudnotes-backend
  namespace: {{ .Release.Namespace | default "default" }}
  annotations:
    iam.gke.io/gcp-service-account: cloudnotes-backend-{{ .Values.global.environment }}@{{ .Values.global.projectId }}.iam.gserviceaccount.com
