apiVersion: v1
kind: Service
metadata:
  name: cloudnotes-worker
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app: cloudnotes-worker
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: cloudnotes-worker
